import { Project } from './types'

export const PROJECTS: Record<string, Project> = {
  ordinary: {
    key: 'ordinary',
    title: 'The Ordinary',
    category: 'Skincare · Rebrand',
    client: 'DECIEM',
    year: '2024',
    role: 'Brand & Digital Lead',
    accent: '#6C2BD9',
    tagline: 'A clinical-beauty rebrand that made transparency the whole point.',
    overview: "We reimagined The Ordinary's digital presence around radical clarity — turning ingredient science into the hero of every touchpoint. The new system spans web, packaging language and campaign assets, built to scale across 30+ markets.",
    challenge: 'A fast-growing catalogue had outpaced the original identity. Shoppers were overwhelmed by choice and unsure which formulas to combine. We needed a system that educated without diluting the no-nonsense brand voice.',
    services: ['Brand Strategy', 'Web Design', 'Content System', 'Campaigns', 'Art Direction'],
    results: [
      { value: '+38%', label: 'Conversion uplift' },
      { value: '2.4M',  label: 'Campaign reach' },
      { value: '30+',   label: 'Markets rolled out' },
    ],
    image: '/images/work-ordinary.png',
  },
  apple: {
    key: 'apple',
    title: 'Apple Inc',
    category: 'Product · Launch',
    client: 'Apple',
    year: '2023',
    role: 'Creative Production',
    accent: '#0B0B0B',
    tagline: 'Launch storytelling that let the product breathe.',
    overview: 'A full launch toolkit for a flagship release — from pre-production and motion direction to web content and in-store activations, unified under one cinematic visual language.',
    challenge: 'Coordinating a synchronized global reveal across film, web and retail meant every frame and pixel had to feel inevitable. The bar for restraint and finish left zero margin for noise.',
    services: ['Creative Direction', 'Film Production', 'Web Content', 'Events & Activations', 'Voice Branding'],
    results: [
      { value: '120M', label: 'Launch-day views' },
      { value: '#1',   label: 'Trending worldwide' },
      { value: '4.9',  label: 'Avg. asset rating' },
    ],
    image: '/images/work-apple.png',
  },
  google: {
    key: 'google',
    title: 'Google LLC',
    category: 'Brand · Voice',
    client: 'Google',
    year: '2024',
    role: 'Brand Strategy',
    accent: '#19b3c6',
    tagline: 'A warmer, more human voice for a product everyone uses.',
    overview: 'We developed a voice-branding framework and content system to make a sprawling product family sound like one helpful, optimistic teammate — across web, campaigns and activations.',
    challenge: 'Dozens of teams shipping copy independently meant tone drifted constantly. We built guardrails flexible enough for engineers and writers alike to use without a style police.',
    services: ['Brand Strategy', 'Voice Branding', 'Design System', 'Web Content', 'Campaigns'],
    results: [
      { value: '8x',   label: 'Faster content sign-off' },
      { value: '92%',  label: 'Internal adoption' },
      { value: '+27%', label: 'Message recall' },
    ],
    image: '/images/work-google.png',
  },
  coke: {
    key: 'coke',
    title: 'The Coca-Cola Company',
    category: 'Brand · Experiential',
    client: 'Coca-Cola',
    year: '2023',
    role: 'Brand & Experience',
    accent: '#19b3c6',
    tagline: 'Turning a global icon into a live, shareable moment.',
    overview: 'An experiential campaign system pairing bold design with real-world activations — designed so every event became content, and every piece of content drove people back to the experience.',
    challenge: "For a brand this recognizable, the risk is sameness. We had to find genuine surprise while staying unmistakably Coca-Cola in every market we touched.",
    services: ['Brand Strategy', 'Experiential Design', 'Digital', 'Events & Activations', 'Content & Campaigns'],
    results: [
      { value: '15M+', label: 'Event attendees' },
      { value: '+44%', label: 'Social engagement' },
      { value: '60',   label: 'Cities activated' },
    ],
    image: '/images/work-coke.png',
  },
  zipto: {
    key: 'zipto',
    title: 'Zipto',
    category: 'Logistics · Web',
    client: 'Zipto Logistics',
    year: '2024',
    role: 'Design & Development',
    accent: '#FF6B35',
    tagline: 'Fast, trackable deliveries — simplified for the digital age.',
    overview: 'We designed and developed the complete web platform for Zipto, a last-mile logistics startup. The site communicates speed and reliability through clean UI, motion-driven onboarding, and a live tracking interface that keeps customers informed from dispatch to doorstep.',
    challenge: 'Logistics platforms traditionally feel clunky and enterprise-heavy. Zipto wanted to feel fast, modern and approachable to individual senders and small businesses alike — without sacrificing the operational depth that power users need.',
    services: ['UI/UX Design', 'Web Development', 'Brand Identity', 'Dashboard Design'],
    results: [
      { value: '40%',  label: 'Drop in support tickets' },
      { value: '3.2x', label: 'Booking conversion rate' },
      { value: '98%',  label: 'On-time delivery tracking' },
    ],
    image: '/images/zipto.png',
    websiteUrl: 'https://zipto.in',
  },
  customer_app: {
    key: 'customer_app',
    title: 'Zipto Customer App',
    category: 'Mobile · Logistics',
    client: 'Zipto Logistics',
    year: '2024',
    role: 'Mobile UI & Product Design',
    accent: '#FF6B35',
    tagline: 'Book, track and manage deliveries — all from your pocket.',
    overview: 'The Zipto customer app lets users book pickups, track deliveries in real-time, and manage payment history from a clean, intuitive interface. Designed for iOS and Android with a focus on speed and ease of use at every step of the delivery journey.',
    challenge: 'First-time users needed to place a booking in under 60 seconds without onboarding friction. We simplified the flow to three taps: pick-up address, drop-off, confirm — with smart address memory and instant price estimation baked in.',
    services: ['Mobile UI Design', 'UX Flow', 'iOS & Android Design', 'Prototype & Handoff'],
    results: [
      { value: '58s',  label: 'Avg. booking time' },
      { value: '4.7★', label: 'App store rating' },
      { value: '+65%', label: 'Day-7 retention' },
    ],
    image: '/images/customer_app.png',
    appStoreUrl: '#',
    playStoreUrl: '#',
  },
  rider_app: {
    key: 'rider_app',
    title: 'Zipto Rider App',
    category: 'Mobile · Operations',
    client: 'Zipto Logistics',
    year: '2024',
    role: 'Mobile UI & Product Design',
    accent: '#FF6B35',
    tagline: 'Empowering riders with real-time data and smart routing.',
    overview: 'The Zipto rider app gives delivery partners a powerful operations tool — live order queue, optimised route navigation, earnings dashboard and in-app dispatch chat. Designed to reduce cognitive load under high-pressure delivery windows.',
    challenge: 'Riders operate in noisy, distracted environments while navigating unfamiliar areas. We prioritised large tap targets, high-contrast visuals and audio cues so they could stay efficient without looking away from the road.',
    services: ['Mobile UI Design', 'UX Research', 'iOS & Android Design', 'Maps Integration'],
    results: [
      { value: '22%',  label: 'Faster route completion' },
      { value: '4.8★', label: 'Rider satisfaction score' },
      { value: '–30%', label: 'Wrong delivery rate' },
    ],
    image: '/images/rider_app.png',
    appStoreUrl: '#',
    playStoreUrl: '#',
  },
  eazydrivez: {
    key: 'eazydrivez',
    title: 'Eazydrivez',
    category: 'Self-Rental · Web',
    client: 'Eazydrivez',
    year: '2024',
    role: 'Full Design & Development',
    accent: '#19b3c6',
    tagline: 'Rent a car or bike on your terms — no hassle, no agent.',
    overview: 'We built the complete web platform for Eazydrivez, a self-rental vehicle service offering cars and bikes on flexible hourly and daily plans. The site handles browse, booking, KYC verification and payment in one seamless flow optimised for mobile-first users.',
    challenge: 'Self-rental platforms live and die on trust and clarity. Users need to understand pricing, availability and pickup logistics instantly. We eliminated every ambiguity in the booking funnel and made transparent pricing the very first thing you see.',
    services: ['UI/UX Design', 'Web Development', 'Booking System', 'Mobile-first Design'],
    results: [
      { value: '2.1x', label: 'Booking conversion' },
      { value: '4.6★', label: 'User satisfaction' },
      { value: '80+',  label: 'Vehicles listed' },
    ],
    image: '/images/eazydrivez.png',
    websiteUrl: 'https://eazydrivez.com/',
  },
  sjdecors: {
    key: 'sjdecors',
    title: 'SJ Decors',
    category: 'Interior Design · Web',
    client: 'SJ Decors',
    year: '2024',
    role: 'Brand & Web Design',
    accent: '#C5F23C',
    tagline: 'Showcasing spaces that feel like stories.',
    overview: "We designed and developed a premium portfolio website for SJ Decors, an interior design studio. The site features an editorial project grid, curated services breakdown and a lead-generation contact flow — all wrapped in a refined visual language that mirrors the studio's taste.",
    challenge: 'Interior design clients buy on emotion and aspiration. The website had to be the portfolio itself — letting photography breathe, keeping navigation invisible, and guiding visitors naturally from inspiration to inquiry.',
    services: ['Brand Identity', 'Web Design', 'Web Development', 'Photography Direction'],
    results: [
      { value: '+3x', label: 'Lead inquiry rate' },
      { value: '92%', label: 'Bounce rate reduced' },
      { value: '15+', label: 'Projects showcased' },
    ],
    image: '/images/sjdecors.png',
    websiteUrl: 'https://www.sjdecors.in/',
  },
}
